<main>
    <h1>Create User</h1>
    <form method="post" action="index.php?route=check_create_user">
        <fieldset>
        <label for="firstName">Prénom : </label>
        <input id="firstName"type="text" name="firstName" required>
        <br>
        <label for="lastName">Nom de famille : </label>
        <input id="lastName"type="text" name="lastName" required>
        <br>
        <label for="email">Email : </label>
        <input id="email" type="email" name="email" required>
        </fieldset>
        <button type="submit">Créer</button>
    </form>
</main>