<main>
    <h1>Liste des Utilisateurs</h1>
    <a href = "index.php?route=create_user">Créer un nouvel utilisateur</a>
    <div class="users-container">
        <ul>
            <?php foreach($data as $user){ ?>
                <li>
                    <section class="user">
                        <h2><?=$user->getFirstName()." ".$user->getLastName()?></h2>
                        <p><?=$user->getEmail()?></p>
                        <ul>
                            <li><a href="index.php?route=show_user&user_id=<?=$user->getId()?>">Afficher les détails</a></li>
                            <li><a href="index.php?route=update_user&user_id=<?=$user->getId()?>">Modifier l'utilisateur</a></li>
                            <li><a href="index.php?route=delete_user&user_id=<?=$user->getId()?>">Supprimer l'utilisateur</a></li>
                        </ul>
                    </section>
                </li>
            <?php }?>
        </ul>
    </div>
</main>