<main>
    <h1>Update User</h1>
    <form method="post" action="index.php?route=check_update_user&user_id=<?=$data["user"]->getId() ?>">
        <fieldset>
        <label for="firstName">Prénom : </label>
        <input id="firstName"type="text" name="firstName" value="<?=$data["user"]->getFirstName() ?>" required>
        <br>
        <label for="lastName">Nom de famille : </label>
        <input id="lastName"type="text" name="lastName" value="<?=$data["user"]->getLastName() ?>"required>
        <br>
        <label for="email">Email : </label>
        <input id="email" type="email" name="email" value="<?=$data["user"]->getEmail() ?>" required>
        </fieldset>
        <button type="submit">Modifier</button>
    </form>
</main>